[profile.default]
solc = '0.8.23'
vm_version = 'paris'                   # Required for L2s (Optimism, Arbitrum, etc.)
sizes = true
verbosity = 3                          # display errors
optimizer_runs = 100000000
block_number = 14126430
block_timestamp = 1643802347
runs = 4096

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
  
