[profile.default]
solc = '0.8.23'
vm_version = 'paris'                   # Required for L2s (Optimism, Arbitrum, etc.)
sizes = true
verbosity = 3                           # display errors
optimizer_runs = 100000000
block_number = 14126430
block_timestamp = 1643802347
runs = 4096
fs_permissions = [{ access = "read", path = "node_modules/@bananapus/core/broadcast/Deploy.s.sol" }, { access = "read", path = "node_modules/@bananapus/721-hook/broadcast/Deploy.s.sol" }, { access = "read", path = "node_modules/@croptop/core/broadcast/Deploy.s.sol" }] # Get the deployment addresses to base the revnets on.

[profile.ci_sizes]
optimizer_runs = 200

[invariant] 
fail_on_revert = false

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true